#!/bin/sh

start()
{

	sleep 30
        [ -f /home/pi/SensorArray/ser.py ] && {
		/usr/bin/git -C /home/pi/SensorArray fetch origin
		/usr/bin/git -C /home/pi/SensorArray reset --hard origin/master
		/usr/bin/python /home/pi/SensorArray/ser.py &>/dev/null
        } || {
                /usr/bin/git clone https://github.com/cclljj/SensorArray/ /root/SensorArray
		/usr/bin/python /home/pi/SensorArray/ser.py &>/dev/null
        }


}

stop()
{
        [ -f /root/AnySense_7688/APP_RESCUE_TW.py ] && {
		rm -rf /home/pi/AnySense_7688
	}
}
